### ISSUE TITLE
Plugin refuse to work when it's installed in a directory with spaces

### ISSUE THREAD

**Issue by sam20908** [cdelledonne/vim-cmake#14] opened 2020-10-14 00:09 UTC
**Describe the bug**
The plugin refuses to generate because my home path contains a space

**To Reproduce**
1. Have a home path with space inside (typically Windows with accounts of full names)
2. Run `:CMakeGenerate`

**Expected behavior**
The project should successfully configure

**Screenshots**
![f783df6cb6ff2cbf2e28fdee15071c3e](https://user-images.githubusercontent.com/18388795/95928623-b04bed00-0d76-11eb-87fb-0d23718eb72f.png)

**Other info**
- OS: Windows 10
- Vim/Neovim version: 0.4.4
- Vim-CMake version (5th line in `:help cmake`): 0.3.0

**Additional context**

**Comment by cdelledonne** [comment] 2020-10-17 15:01
Hi, thanks for reporting the problem.

I've tried to reproduce it on Linux, and there is actually no issue. I created a project inside a directory with path `/home/cdelledonne/Developer/Directory with spaces/Test project`, then ran ":CMakeGenerate" from inside of `Test project`, and I got a normal, successful output:

```
cmake -DCMAKE_BUILD_TYPE=Debug -S . -B Debug
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cdelledonne/Developer/Directory with spaces/Test project/Debug
```

The problem must be with Windows refusing to run the bash script that powers the Vim-CMake console (the script being `scripts/console.sh`). As mentioned in the README, Windows is not supported yet. I haven't thought of a way to run this bash script on Windows, as my knowledge of it is quite limited.

I'm closing this issue as the problem is different than what is described. Please feel free to open a feature request and ask for support for Windows. Maybe somebody has some suggestions as to how to approach it. Perhaps you could even look into it, if you feel like it.

**Comment by cdelledonne** [comment] 2020-10-17 15:08
EDIT: actually the directory with spaces creates trouble when the plugin itself is inside a path with spaces. I'm reopening the issue as I should look into this as well. But the problem with Windows remains.

**Comment by sam20908** [comment] 2020-10-17 15:33
Thank you very much for putting effort to investigate this! I really appreciate it 👍

**Comment by sam20908** [comment] 2020-10-17 18:34
I'll rename the title of this issue to reflect the actual issue 👍

**Closed** 2020-10-31 18:52 UTC
Labels: bug

**Comment by sam20908** [comment] 2020-10-31 22:22
Can confirm it works! 👍

**Comment by cdelledonne** [comment] 2020-11-01 09:48
Out of curiosity, on which platform/terminal did you test it?

**Comment by sam20908** [comment] 2020-11-01 14:06
I tested it on Windows 😉 . I mainly use the Windows Terminal.
