### ISSUE TITLE
issue with neovim 0.3.0 bundled with CentOS 7

### ISSUE THREAD

**Issue by snikulov** [cdelledonne/vim-cmake#3] opened 2020-06-25 13:18 UTC
**Describe the bug**
The plugin is not working on CentOS7 / neovim v0.3.0 / cmake v3.17.2

**Error:**
Error detected while processing function cmake#Generate[16]..cmake#generate#Run:                                          
line    8:                                                                                                                
E121: Undefined variable: s:cmake_version                                                                                 
E15: Invalid expression: s:cmake_version < 313 

**To Reproduce**
1. Install CMake plugin using vim-plug ```Plug 'cdelledonne/vim-cmake'```
2. Try to generate project using :CMakeGenerate (I'm in the top-level project directory and no build folder present)

**Expected behavior**
No errors - folder ```build``` created, generated files appear in it. 

**Screenshots**
![nvim_cmake_issue](https://user-images.githubusercontent.com/142123/85727712-eb5edd80-b6ff-11ea-8fe7-acb7e5989fdb.png)

**Other info**
- OS: 
> cat /etc/centos-release 
CentOS Linux release 7.7.1908 (Core)
- Vim/Neovim version:
> nvim --version
```
NVIM v0.3.0
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -Wconversion -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/builddir/build/BUILD/neovim-0.3.0/build/config -I/builddir/build/BUILD/neovim-0.3.0/src -I/usr/include -I/builddir/build/BUILD/neovim-0.3.0/build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.3.0/build/include
Compiled by mockbuild

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Vim-CMake version (5th line in `:help cmake`): 
Version:        0.1.1 

**Additional context**

**Comment by cdelledonne** [comment] 2020-06-26 08:28
Hi, thank you for reporting the issue.

I downloaded Nvim 0.3.0 to try to reproduce the issue, but that error doesn't seem to occur to me. I did find another problem though, for which I created a pull request. Out of curiosity, have you tried a newer Nvim on the same machine?

Otherwise, would you be willing to help me debug your issue?

**Comment by snikulov** [comment] 2020-06-29 08:33
> Out of curiosity, have you tried a newer Nvim on the same machine?

No. I've used pre-built neovim from CentOS 7 repository

```
$ dnf info neovim
Installed Packages
Name         : neovim
Version      : 0.3.0
Release      : 2.el7
Arch         : x86_64
Size         : 19 M
Source       : neovim-0.3.0-2.el7.src.rpm
Repo         : @System
From repo    : epel
```
> Otherwise, would you be willing to help me debug your issue?

How I can help you?

**Comment by cdelledonne** [comment] 2020-06-29 13:43
> How I can help you?

1. Checkout the branch `nvim-0-3-0-compat` of this plugin:
    ```vim
    Plug 'cdelledonne/vim-cmake', { 'branch': 'nvim-0-3-0-compat' }
    ```
    then remember to source your `init.vim` and run `:PlugUpdate`
2. Relaunch `nvim`, and run `:CMakeGenerate`

I added some debug messages, you should hopefully see them appearing in Nvim. If so, please send me a screenshot of that.

Thanks!

**Comment by cdelledonne** [comment] 2020-07-06 17:07
@snikulov I launched a VM running CentOS 7, and installed Nvim (0.3.0) from the EPEL repository. I was not able to reproduce the issue, Vim-CMake works as expected.

I'm closing this issue, the problem might have to do with something other than Nvim or this plugin.

**Closed by cdelledonne** 2020-07-06 17:07 UTC
Labels: bug, cant reproduce
