### ISSUE TITLE
Weird project root path

### ISSUE THREAD

**Issue by ravenxrz** [cdelledonne/vim-cmake#44] opened 2022-03-23 13:30 UTC
### Bug description

I got a weird project root path output after I run CMakeGenerate:

![image](https://user-images.githubusercontent.com/44746032/159711115-786396ac-461f-490d-9396-2eb89073e72a.png)

the pwd is: /home/rave/tmp/test_project, but the project root path is pwd followed by a white space, which does not exist.

### To Reproduce
1. open project
2. Type `CMakeGenerate`

### Expected behavior

cmake build success.

### Behavior with minimal `.vimrc`
my vim-cmake config:
```
    let g:cmake_link_compile_commands = 1
    let g:cmake_build_dir_location = './build'
    let g:cmake_build_options= ["-j8"]
    let g:cmake_log_file="/tmp/vim-cmake.log"
```

### Screenshots

see `Bug description` section.

### Other info
- OS: Ubuntu 20.04
- Vim/Neovim version: nvim v0.6.1
- Vim-CMake version (5th line in `:help cmake`): 0.7.0

### Log output

```
[2022-03-23 21:22:53] [ INFO] Loading Vim-CMake
[2022-03-23 21:22:53] [ INFO] Commands defined
[2022-03-23 21:22:53] [ INFO] Mappings defined
[2022-03-23 21:22:53] [ INFO] Vim-CMake loaded
[2022-03-23 21:22:56] [ INFO] Project root: /home/raven/tmp/test_project
[2022-03-23 21:22:56] [ INFO] Current config: Debug (/home/raven/tmp/test_project/build/Debug)
[2022-03-23 21:22:56] [DEBUG] Invoked: statusline.SetBuildInfo(Debug)
[2022-03-23 21:22:56] [DEBUG] Build configs: []
[2022-03-23 21:22:56] [ INFO] Configuration options:
[2022-03-23 21:22:56] [ INFO] > g:cmake_build_dir_location: './build'
[2022-03-23 21:22:56] [ INFO] > g:cmake_build_options: ['-j8']
[2022-03-23 21:22:56] [ INFO] > g:cmake_command: 'cmake'
[2022-03-23 21:22:56] [ INFO] > g:cmake_console_echo_cmd: 1
[2022-03-23 21:22:56] [ INFO] > g:cmake_console_position: 'botright'
[2022-03-23 21:22:56] [ INFO] > g:cmake_console_size: 15
[2022-03-23 21:22:56] [ INFO] > g:cmake_default_config: 'Debug'
[2022-03-23 21:22:56] [ INFO] > g:cmake_generate_options: []
[2022-03-23 21:22:56] [ INFO] > g:cmake_jump: 0
[2022-03-23 21:22:56] [ INFO] > g:cmake_jump_on_completion: 0
[2022-03-23 21:22:56] [ INFO] > g:cmake_jump_on_error: 1
[2022-03-23 21:22:56] [ INFO] > g:cmake_link_compile_commands: 1
[2022-03-23 21:22:56] [ INFO] > g:cmake_log_file: '/tmp/vim-cmake.log'
[2022-03-23 21:22:56] [ INFO] > g:cmake_native_build_options: []
[2022-03-23 21:22:56] [ INFO] > g:cmake_root_markers: ['.git', '.svn']
[2022-03-23 21:22:56] [DEBUG] API invoked: cmake#Generate(0, [])
[2022-03-23 21:22:56] [DEBUG] Invoked: buildsys.Generate(0, '')
[2022-03-23 21:22:56] [DEBUG] Invoked: terminal.Run(['cmake', '-D CMAKE_BUILD_TYPE=Debug', '-D CMAKE_EXPORT_COMPILE_COMMANDS=ON', '-S .', '-B build/Debug'], 'generate', [function('<SNR>80_RefreshConfigs'), function('<SNR>80_RefreshTargets'), function('<SNR>80_LinkCompileCommands')], [function('<SNR>80_RefreshConfigs')], [], [])
[2022-03-23 21:22:56] [DEBUG] Invoked: terminal.Open(v:false)
[2022-03-23 21:22:56] [DEBUG] Created console window
[2022-03-23 21:22:57] [DEBUG] Invoked: statusline.SetCmdInfo(Generating buildsystem...)
[2022-03-23 21:22:57] [DEBUG] Invoked console exit callback
[2022-03-23 21:22:57] [DEBUG] Invoked: statusline.SetCmdInfo()
[2022-03-23 21:22:57] [DEBUG] Invoked: terminal.Focus()
[2022-03-23 21:22:57] [DEBUG] Callback invoked: <SNR>80_RefreshConfigs()
[2022-03-23 21:22:57] [DEBUG] Build configs: []
[2022-03-23 21:23:01] [ INFO] Loading Vim-CMake
[2022-03-23 21:23:01] [ INFO] Commands defined
[2022-03-23 21:23:01] [ INFO] Mappings defined
[2022-03-23 21:23:01] [ INFO] Vim-CMake loaded
```

**Comment by loftyhauser** [comment] 2022-03-24 21:09
I'm getting exactly the same on Mint 18 (Ubuntu 20.04), with vim-cmake 0.7 and vim 8.1.  I con't have any vim-cmake configuration customizations.

**Comment by cdelledonne** [comment] 2022-03-28 08:13
Hey, thanks for opening this.

I cannot reproduce the problem, perhaps that has to do with some underlying system configuration. Let me think of a way to debug this and get back to you in a few days.

In the meantime, could you tell me which shell you're using?

**Comment by ravenxrz** [comment] 2022-03-28 09:13
> Hey, thanks for opening this.
> 
> I cannot reproduce the problem, perhaps that has to do with some underlying system configuration. Let me think of a way to debug this and get back to you in a few days.
> 
> In the meantime, could you tell me which shell you're using? @ravenxrz @loftyhauser

I use gnome-shell with zsh.

**Comment by loftyhauser** [comment] 2022-03-28 12:28
> In the meantime, could you tell me which shell you're using? @ravenxrz @loftyhauser

I'm using XFCE with bash; I've also seen the problem on a Suse system with bash.  The strange thing is that (on the Suse system) I commented out just about everything in my .vimrc and retried the cmake plugin commands, and did *not* see the problem.  So I tried again on the Suse system (with the minimal .vimrc) and *did* see the problem again.  I'm going to do some more digging to see what might be the problem...

**Comment by loftyhauser** [comment] 2022-03-28 21:27
It appears the problem is the version of CMake that comes with Ubuntu 20.04 (probably a change in behavior with newer versions).  The plugin problem is present on clean installs of Ubuntu 20.04 (vim 8.1 and cmake 3.16) and Debian 11 (vim 8.2 and cmake 3.18), but not on Fedora 35 (vim 8.2 and cmake 3.22).  I compiled cmake-3.23.0rc5 on my Mint machine and the vim-cmake plugin appears to be working correctly now.

**Comment by ravenxrz** [comment] 2022-03-29 04:41
> compiled cmake-3.23.0rc5 on my Mint machine and the vim-cmake plugin appears to be working correctly now.

Thank you. I have verified version 3.23.0-rc5 works on Ubuntu20.04 too. 

Wait for @cdelledonne to fix this.

**Comment by cdelledonne** [comment] 2022-03-29 11:29
@loftyhauser thanks a lot for the thorough investigation, and @ravenxrz thanks for confirming that. I'll try to find some time this weekend to install an older CMake and debug the issue.

**Comment by cdelledonne** [comment] 2022-04-02 11:22
@ravenxrz @loftyhauser I've pushed a fix on the branch `44-weird-project-root-path`, could you please try if that fixes your problem? Thanks in advance.

**Comment by ravenxrz** [comment] 2022-04-02 11:54
> @ravenxrz @loftyhauser I've pushed a fix on the branch `44-weird-project-root-path`, could you please try if that fixes your problem? Thanks in advance.

It works on my WSL with CMake version 3.16.3 now. Thank you.

**Comment by loftyhauser** [comment] 2022-04-02 12:33
I've also verified that the fix works for the standard cmake and vim versions that come with Ubuntu 20.04 (vim 8.1 and cmake 3.16) as well as newer versions (vim 8.2 and cmake 3.23).  Thanks!

**Comment by cdelledonne** [comment] 2022-04-02 15:24
Great, then I'll merge :)

**Closed** 2022-04-02 15:25 UTC
Labels: bug
